#!/bin/bash
# scripts/package-arch.sh
# Packages Nexus Play for Arch Linux (bin / AUR packaging helper)

set -e

echo "=== [Arch Packaging] Starting Nexus Play build ==="
cd "$(dirname "$0")/.."

# 1. Run monorepo build
npm run build

# 2. Package with electron-builder
echo "=== [Arch Packaging] Packaging binary files ==="
npm run package --workspace=apps/desktop

# 3. Generate PKGBUILD folder structure
echo "=== [Arch Packaging] Generating PKGBUILD configuration ==="
mkdir -p dist/arch-package
cat << 'EOF' > dist/arch-package/PKGBUILD
# Maintainer: Abdullah <abdullah@nexus-play.org>
pkgname=nexus-play-bin
pkgver=0.1.0
pkgrel=1
pkgdesc="Unified Electron Game Launcher for Arch Linux (Steam, Epic, and manual entries)"
arch=('x85_64')
url="https://github.com/abdullah/nexus-play"
license=('MIT')
depends=('electron' 'nodejs' 'sqlite' 'libsecret' 'xdg-utils')
optdepends=(
  'steam: Steam library detection'
  'legendary: Epic Games Store CLI client'
  'lutris: Lutris prefixes launcher support'
  'gamemode: Feral Interactive GameMode optimization'
  'mangohud: MangoHud overlay for FPS and performance monitoring'
)
provides=('nexus-play')
conflicts=('nexus-play')
source_x86_64=("nexus-play-${pkgver}-x86_64.pacman")
sha256sums_x86_64=('SKIP')

package() {
  # Pacman packages generated by electron-builder already contain the full package structure
  # Here we extract and place files accordingly
  tar -xvf "${srcdir}/nexus-play-${pkgver}-x86_64.pacman" -C "${pkgdir}/"
}
EOF

echo "=== [Arch Packaging] Done. PKGBUILD generated in dist/arch-package/PKGBUILD ==="
